### ISSUE TITLE
DOMParser undefined in Angular 17 with SSR

### ISSUE THREAD

**Issue by emcdaniel1624** [korywka/mapbox-controls#50]
I am trying to use the styles control in an angular 17 application that is using server side rendering. When adding the control I get the error 

Error when evaluating SSR module /main.server.mjs:
|- ReferenceError: DOMParser is not defined
    at parseSVG (c:/Users/ethan.mcdaniel/source/repos/Traction/SmartPriority/traction-priority/node_modules/@mapbox-controls/helpers/src/index.js:53:3)
    at eval (c:/Users/ethan.mcdaniel/source/repos/Traction/SmartPriority/traction-priority/node_modules/@mapbox-controls/styles/src/icons.js:2:16)
    at async instantiateModule (file:///C:/Users/ethan.mcdaniel/source/repos/Traction/SmartPriority/traction-priority/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:9)

**Comment by korywka** [comment]
Hello. MapBox controls are not SSR-able. They use browser DOM and should be excluded while SSR on the server.

I suggest to exclude all the MapBox map component (canvas) from SSR too.
